<x-layouts.app>
    @section('title', 'Verification queue | Listora.ng')
    @section('app_title', 'Verifications')
    @section('app_back', route('admin.dashboard'))
    <section class="mx-auto max-w-[1000px]">
        <x-mobile-page-header title="Verification queue" subtitle="Review identity and business submissions." />
        <nav class="flex gap-2 overflow-x-auto pb-2" aria-label="Verification status">@foreach(['submitted' => 'Pending', 'under_review' => 'Under Review', 'action_required' => 'Action Required', 'approved' => 'Approved', 'rejected' => 'Rejected'] as $value => $label)<a href="{{ route('admin.verifications.index', ['status' => $value]) }}" class="shrink-0 rounded-lg border px-3 py-2 text-sm font-medium {{ $status === $value ? 'border-[#145FCC] bg-[#EAF2FF] text-[#0A2856]' : 'border-[#E4E7EC] bg-white text-[#475467]' }}">{{ $label }} <span class="ml-1 text-xs">{{ $counts[$value] ?? 0 }}</span></a>@endforeach</nav>
        <div class="mt-3 grid gap-3">@forelse($requests as $item)<article class="rounded-xl border border-[#E4E7EC] bg-white p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h2 class="truncate font-semibold">{{ $item->user->agent?->display_name ?: $item->user->name }}</h2><p class="mt-1 text-sm text-[#667085]">{{ str($item->verification_type)->replace('_', ' ')->title() }}</p></div><x-status-badge>{{ str($item->status)->headline() }}</x-status-badge></div><dl class="mt-3 grid grid-cols-2 gap-3 text-sm md:grid-cols-3"><div><dt class="text-xs text-[#667085]">Location</dt><dd class="mt-1">{{ collect([$item->user->agent?->operating_city, $item->user->agent?->operating_state])->filter()->join(', ') ?: 'Not provided' }}</dd></div><div><dt class="text-xs text-[#667085]">Submitted</dt><dd class="mt-1">{{ $item->submitted_at?->format('j M Y') ?: 'Draft' }}</dd></div>@if($item->organization?->cac_registration_number)<div><dt class="text-xs text-[#667085]">CAC number</dt><dd class="mt-1">{{ $item->organization->cac_registration_number }}</dd></div>@endif</dl><a href="{{ route('admin.verifications.show', $item) }}" class="btn-primary mt-4 w-full sm:w-auto">Review</a></article>@empty<x-empty-state icon="shield-check" title="No requests here" message="New verification requests will appear in this queue." />@endforelse</div>{{ $requests->links() }}
    </section>
</x-layouts.app>
