<x-layouts.public>
    @section('title', 'Review verification | Listora.ng')
    <section class="dashboard-shell"><a href="{{ route('admin.verifications.index') }}" class="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-[#145FCC]"><x-icon name="arrow-left" />Back to queue</a>
        @if(session('status'))<p class="mb-4 rounded-lg bg-[#EAF2FF] p-3 text-sm text-[#0A2856]">{{ session('status') }}</p>@endif
        <div class="grid gap-5 lg:grid-cols-[1fr_360px]"><div class="rounded-xl border border-[#E4E7EC] bg-white p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-sm text-[#667085]">{{ str($verificationRequest->verification_type)->replace('_',' ')->title() }}</p><h1 class="text-[27px] font-semibold text-[#182230]">{{ $verificationRequest->user->agent?->display_name ?: $verificationRequest->user->name }}</h1></div><x-status-badge>{{ str($verificationRequest->status)->headline() }}</x-status-badge></div>
            <dl class="mt-5 grid gap-3 text-sm sm:grid-cols-2">@foreach(['Account owner'=>$verificationRequest->user->name,'Email'=>$verificationRequest->user->email,'Phone'=>'+'.$verificationRequest->user->phone,'Location'=>collect([$verificationRequest->user->agent?->operating_city,$verificationRequest->user->agent?->operating_state])->filter()->join(', '),'Business'=>$verificationRequest->organization?->name,'CAC number'=>$verificationRequest->organization?->cac_registration_number] as $label=>$value)@if($value)<div class="rounded-lg bg-[#F7F8FA] p-3"><dt class="text-xs text-[#667085]">{{ $label }}</dt><dd class="mt-1 font-medium text-[#182230]">{{ $value }}</dd></div>@endif @endforeach</dl>
            <h2 class="mt-6 text-lg font-semibold">Private documents</h2><div class="mt-3 grid gap-2">@foreach($verificationRequest->documents as $document)<a href="{{ $documentUrls[$document->id] }}" target="_blank" rel="noopener" class="flex min-h-12 items-center justify-between rounded-lg border border-[#E4E7EC] px-3 text-sm font-medium text-[#145FCC]"><span>{{ str($document->document_type)->headline() }} · {{ $document->original_filename }}</span><x-icon name="eye" /></a>@endforeach</div>
        </div>
        <aside class="rounded-xl border border-[#D7E2F4] bg-white p-4"><h2 class="text-lg font-semibold">Decision</h2><form method="POST" class="mt-3" action="{{ route('admin.verifications.approve',$verificationRequest) }}">@csrf<label class="form-label">Reviewer note <span class="font-normal text-[#667085]">Optional</span></label><textarea name="reviewer_note" rows="3" class="form-input"></textarea><button class="btn-primary mt-3 w-full">Approve</button></form><form method="POST" class="mt-5 border-t border-[#E4E7EC] pt-4" action="{{ route('admin.verifications.correction',$verificationRequest) }}">@csrf<label class="form-label">Correction message</label><textarea name="reviewer_note" rows="3" class="form-input" required></textarea><p class="mt-2 text-xs text-[#667085]">Select documents that should be replaced.</p>@foreach($verificationRequest->documents as $document)<label class="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" name="rejected_documents[]" value="{{ $document->id }}" class="size-4">{{ str($document->document_type)->headline() }}</label>@endforeach<button class="btn-secondary mt-3 w-full">Request correction</button></form><form method="POST" class="mt-5 border-t border-[#E4E7EC] pt-4" action="{{ route('admin.verifications.reject',$verificationRequest) }}">@csrf<label class="form-label">Reason for rejection</label><textarea name="reviewer_note" rows="3" class="form-input" required></textarea><button class="mt-3 min-h-12 w-full rounded-lg border border-[#C92A2A] text-sm font-medium text-[#C92A2A]">Reject</button></form></aside></div>
    </section>
</x-layouts.public>
