<x-layouts.app>
    @section('title', 'Review verification | Listora.ng')
    @section('app_title', 'Review verification')
    @section('app_back', route('admin.verifications.index'))
    <section class="mx-auto max-w-[1050px]">
        @if(session('status'))<p class="mb-4 rounded-lg bg-[#EAF2FF] p-3 text-sm text-[#0A2856]">{{ session('status') }}</p>@endif
        <div class="sticky bottom-[3.625rem] z-20 -mx-4 mb-4 flex gap-2 border-y border-[#E4E7EC] bg-white p-3 shadow-[0_-2px_10px_rgba(10,40,86,.05)] lg:hidden"><form method="POST" class="flex-1" action="{{ route('admin.verifications.approve', $verificationRequest) }}">@csrf<button class="btn-primary w-full">Approve</button></form><a href="#review-actions" class="btn-secondary flex-1">Other actions</a></div>
        <div class="grid gap-5 lg:grid-cols-[1fr_360px]">
            <div class="rounded-xl border border-[#E4E7EC] bg-white p-4 md:p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-sm text-[#667085]">{{ str($verificationRequest->verification_type)->replace('_', ' ')->title() }}</p><h1 class="mt-1 text-[23px] font-semibold tracking-tight md:text-[28px]">{{ $verificationRequest->user->agent?->display_name ?: $verificationRequest->user->name }}</h1></div><x-status-badge>{{ str($verificationRequest->status)->headline() }}</x-status-badge></div>
                <dl class="mt-5 grid gap-3 text-sm sm:grid-cols-2">@foreach(['Account owner' => $verificationRequest->user->name, 'Email' => $verificationRequest->user->email, 'Phone' => '+'.$verificationRequest->user->phone, 'Location' => collect([$verificationRequest->user->agent?->operating_city, $verificationRequest->user->agent?->operating_state])->filter()->join(', '), 'Business' => $verificationRequest->organization?->name, 'CAC number' => $verificationRequest->organization?->cac_registration_number, 'ID type' => data_get($verificationRequest->identity_data, 'id_type'), 'ID number' => data_get($verificationRequest->identity_data, 'id_number')] as $label => $value)@if($value)<div class="rounded-lg bg-[#F7F8FA] p-3"><dt class="text-xs text-[#667085]">{{ $label }}</dt><dd class="mt-1 break-words font-medium">{{ str($value)->headline() }}</dd></div>@endif @endforeach</dl>
                <h2 class="mt-6 text-[17px] font-semibold">Private documents</h2><div class="mt-3 grid gap-2">@forelse($verificationRequest->documents as $document)<a href="{{ $documentUrls[$document->id] }}" target="_blank" rel="noopener" class="flex min-h-12 items-center justify-between rounded-lg border border-[#E4E7EC] px-3 text-sm font-medium text-[#145FCC]"><span class="min-w-0 truncate">{{ str($document->document_type)->headline() }} · {{ $document->original_filename }}</span><x-icon name="eye" class="ml-2 shrink-0" /></a>@empty<p class="text-sm text-[#667085]">No documents were uploaded.</p>@endforelse</div>
            </div>
            <aside id="review-actions" class="scroll-mt-5 rounded-xl border border-[#D7E2F4] bg-white p-4 lg:sticky lg:top-6 lg:self-start"><h2 class="text-[17px] font-semibold">Decision</h2><form method="POST" class="mt-3 hidden lg:block" action="{{ route('admin.verifications.approve', $verificationRequest) }}">@csrf<label class="form-label">Reviewer note <span class="font-normal text-[#667085]">Optional</span></label><textarea name="reviewer_note" rows="3" class="form-input"></textarea><button class="btn-primary mt-3 w-full">Approve</button></form><form method="POST" class="mt-3 lg:mt-5 lg:border-t lg:border-[#E4E7EC] lg:pt-4" action="{{ route('admin.verifications.correction', $verificationRequest) }}">@csrf<label class="form-label">Correction message</label><textarea name="reviewer_note" rows="3" class="form-input" required></textarea><p class="mt-2 text-xs text-[#667085]">Select documents that should be replaced.</p>@foreach($verificationRequest->documents as $document)<label class="mt-2 flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="rejected_documents[]" value="{{ $document->id }}" class="size-4">{{ str($document->document_type)->headline() }}</label>@endforeach<button class="btn-secondary mt-3 w-full">Request correction</button></form><form method="POST" class="mt-5 border-t border-[#E4E7EC] pt-4" action="{{ route('admin.verifications.reject', $verificationRequest) }}">@csrf<label class="form-label">Reason for rejection</label><textarea name="reviewer_note" rows="3" class="form-input" required></textarea><button class="mt-3 min-h-12 w-full rounded-lg border border-[#C92A2A] text-sm font-medium text-[#C92A2A]">Reject</button></form></aside>
        </div>
    </section>
</x-layouts.app>
